[package]
name = "grpc-test"
version = "0.1.0"
edition = "2021" # Updated to 2021 for compatibility

[dependencies]
tonic = "0.11"
tokio = { version = "1.37", features = ["full"] }
prost = "0.12"
rand = "0.8" # Add this dependency

[build-dependencies]
tonic-build = "0.11"