FROM rust:latest AS builder

WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y protobuf-compiler
COPY src src
COPY proto proto
COPY build.rs Cargo.toml Cargo.lock ./
RUN cargo build --release --bin client

FROM debian:latest
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/target/release/client .

CMD ["./client"]
