FROM rust:latest AS builder

WORKDIR /usr/src/app
COPY . .

RUN apt-get update && apt-get install -y protobuf-compiler
RUN cargo build --release --bin client

FROM debian:latest
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/target/release/client .

CMD ["./client"]
