apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      initContainers:
        - name: dns-check
          image: busybox
          command:
            - "sh"
            - "-c"
            - |
              echo "Checking /etc/resolv.conf:"
              cat /etc/resolv.conf
              echo "Attempting DNS resolution..."
              nslookup grpc-server-service.default.svc.cluster.local
      containers:
        - name: grpc-client
          image: localhost/grpc-client:latest
          imagePullPolicy: Never
          env:
          - name: GRPC_SERVER_ADDRESS
            value: "http://grpc-server-service.default.svc.cluster.local:50051"
