apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: localhost/grpc-client:latest
          imagePullPolicy: Never
          env:
          - name: GRPC_SERVER_ADDRESS
            value: "http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80"
