apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        resolver kube-dns.kube-system.svc.cluster.local valid=5s; # Use Kubernetes DNS resolver

        upstream grpc-backend {
            zone grpc-backend-zone 64k; # Define shared memory zone for dynamic resolution
            server grpc-server-service.default.svc.cluster.local:50051 resolve; # Use FQDN for service resolution
        }

        server {
            listen 80;
            http2 on;

            location / {
                grpc_pass grpc://grpc-backend;
                error_page 502 = /error502grpc;
            }

            location = /error502grpc {
                internal;
                default_type application/grpc;
                add_header grpc-status 14;
                add_header content-length 0;
                return 204;
            }
        }
    }
