apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
  labels:
    app: grpc-server
spec:
  type: ClusterIP
  selector:
    app: grpc-server
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051

